# Generated by Django 4.2.5 on 2023-09-06 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Tank', 'Танки'), ('Heal', 'Хилы'), ('DD', 'ДД'), ('Trader', 'Торговцы'), ('Guildmaster', 'Гилдмастеры'), ('Questgiver', 'Квестгиверы'), ('Blacksmith', 'Кузнецы'), ('Tanner', 'Кожевники'), ('Potionmaster', 'Зельевары'), ('Spellmaster', 'Мастера заклинаний')], default='Tank', max_length=12, verbose_name='Категория')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('postUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsePost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Board.post', verbose_name='Объявление')),
                ('responseUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
