# Generated by Django 4.2.5 on 2023-09-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='text',
            field=models.TextField(default='Текст по умолчанию', verbose_name='Текст отклика'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Текст объявления'),
        ),
    ]
