# Generated by Django 4.2.5 on 2023-09-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0002_response_text_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Статус принятия отклика автором объявления'),
        ),
    ]
